#ifndef LILY_AST_PARSER_RECOVERY_TYPES_H
#define LILY_AST_PARSER_RECOVERY_TYPES_H

typedef enum {
    RECOVERY_NONE,
    RECOVERY_DECL,
    RECOVERY_STMT,
    RECOVERY_EXPR,
    RECOVERY_TYPE,
    RECOVERY_BLOCK
} RecoveryKind;

#endif // !LILY_AST_PARSER_RECOVERY_TYPES_H
